### ISSUE TITLE
TODO list for the next time I work on this.

### ISSUE THREAD

**Issue by DrewNaylor** [DrewNaylor/Retiled#248]
- [ ] Implement signals and slots in QML so that appbar drawer (and eventually appbar) items can send the `command`s to the app instead of just outputting the text in the console.
  - [ ] Add support for `command` arguments, too, so for example the command is `pin` and the argument is `batterysaver.qml`, thus pinning the page, and another one can be `pin` and `storage.qml`, so then that other page gets pinned.
- [ ] Have the settings app be able to change settings in the config files instead of requiring a text editor to change the settings.
- [ ] Write scripts to copy the "real" versions of libraries like `settingsReader.py` into the `libs` subfolder for each app that uses a given library instead of having to manually copy and paste each time I make a change.
- [ ] Split out common code for like loading theme stuff from each app's `main.py` so it passes the correct relative path (will probably need to also add `os.getcwd()` to the beginning of the relative path) to the code that loads the theme files which will be relocated to a subfolder in each app's `libs` folder (will use the script above to copy into each folder from a main copy).
- [ ] Write a note saying that I'm keeping the search-related stuff in the Settings app for now whenever I'll need to start another app from Settings (unless I don't have the right code? very possible because I think it's just web browser-related, but then again, would I ever need to open the default browser from Settings? unless setting up accounts is something I'd need. yeah, I think I'll keep it and just add a note). I do need to add code to launch other apps probably eventually though, it's the way of the settings app.
